apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: proyecto-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: proyecto-backend
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
