apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: proyecto-backend
type: Opaque
stringData:
  DB_PASSWORD: "password123"
  AWS_ACCESS_KEY_ID: "dummy_access_key"
  AWS_SECRET_ACCESS_KEY: "dummy_secret_key"
